### PR TITLE
sign up: add members/lwhile.md

### PR DESCRIPTION
**Pull request by lwhile**

### CODE REVIEW

**Comment by jolestar** [comment]
pr 文件中的 telegram id 和 discord id 没有修改

**Comment by lwhile** [comment]
抱歉, fixed @jolestar

**Comment by nkysg** [comment]
@lwhile 有成果后，准备好申请reviw可以@nkysg

**Comment by geometryolife** [comment]
Since the PR is not updated for too long, it is temporarily closed. If you want to continue to participate in Startrek, please apply again.

**Pull request closed without merging**
