### PR TITLE
Add Member NaokiLH

### PR DESCRIPTION
**Pull request by NaokiLH**
Sign up startrek plan

### CODE REVIEW

**Comment by yubing744** [comment]
👌

**Comment by NaokiLH** [comment]
@yubing744 Sure. But i don't know typescrip😿. What can i do?

**Comment by yubing744** [comment]
@NaokiLH If you can contribute 3 PRs to the move-analyzer module, you can graduate.

**Comment by yubing744** [comment]
@NaokiLH Hello, how are you studying now?

Graduation criteria have been updated recently, and graduation is now easier: https://github.com/movefuns/web3startrek/blob/main/README.md#graduation-criteria

**Comment by geometryolife** [comment]
Since the PR is not updated for too long, it is temporarily closed. If you want to continue to participate in Startrek, please apply again.

**Pull request closed without merging**
