### PR TITLE
add member: qiwihui

### PR DESCRIPTION
**Pull request by qiwihui**

### CODE REVIEW

**Comment by qiwihui** [comment]
@WGB5445 Could you help to verify me if I could graduate? Thanks a lot.

**Comment by qiwihui** [comment]
cc @jolestar

**Review by geometryolife — APPROVED** [review]

**Review by jiangying000 — APPROVED** [review]

**Comment by jolestar** [comment]
@qiwihui Choose one or two mentors who have helped you the most.

**Comment by qiwihui** [comment]
> @qiwihui Choose one or two mentors who have helped you the most.

I would say @jiangying000 and @0xpause helped me the most.

**Comment by jolestar** [comment]
🎉 Graduated with Level 3


```
curl 'http://main.seed.starcoin.org/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","method":"contract.call_v2","params":[{"function_id":"0x00000000000000000000000000000001::PriceOracle::read","args":["0x82e35b34096f32c42061717c06e44a59"],"type_args":["0x00000000000000000000000000000001::STCUSDOracle::STCUSD"]}],"id":0}'
{"jsonrpc":"2.0","result":[40565],"id":0}
```

```
1000/0.040565 = 24652 STC
```

https://stcscan.io/main/transactions/detail/0xb90d8854272e5160d52b2dd475ef121d8799b448951759981b9fdfe32d8619ed

@jiangying000 1232.5 STC 0x21509f5e983d61e60cb081fa9481e494ac9951f2ed0a8dbe46114652a194fdc3
@0xpause 1232.5 STC 0x9c20c4979762a8426ff0906ac86fe51a931f150f7a03217cfcae25a67a5a7502

**Comment by jolestar** [comment]
Mentors did not give the graduated level in this PR. In the future, mentors should suggest the graduated level @movefuns/dev when reviewing.

**Pull request merged**
