### PR TITLE
Create nangongamo.md

### PR DESCRIPTION
**Pull request by nangongamo**
提交报名申请

### CODE REVIEW

**Comment by nangongamo** [comment]
@jolestar 申请毕业

**Comment by nangongamo** [comment]
感谢@jiangying000 @geometryolife 两位导师在我学习过程中给予的帮助，也谢谢 @jolestar 王老师

**Review by jiangying000 — APPROVED** [review]
thanks, I think at least L2 graduation, feasible to take Starcoin additional grant based on `starcoin-java` related contribution.

**Review by geometryolife — APPROVED** [review]
Congratulations on graduating from L2 @nangongamo 🎓
@jolestar

**Comment by jolestar** [comment]
```
curl 'http://main.seed.starcoin.org/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","method":"contract.call_v2","params":[{"function_id":"0x00000000000000000000000000000001::PriceOracle::read","args":["0x82e35b34096f32c42061717c06e44a59"],"type_args":["0x00000000000000000000000000000001::STCUSDOracle::STCUSD"]}],"id":0}'
{"jsonrpc":"2.0","result":[36722],"id":0}

1000UST/0.036722 = 27232 STC
```

https://stcscan.io/main/transactions/detail/0x8cd9847b28543f6a76d664aa9bafcf484e05fdc67b38fb82f9e3ea61752585d1

@jiangying000 1361.6 STC https://stcscan.io/main/transactions/detail/0xc775b97639e7115e647950b3838d8459fd5a1f3908527f97e8593b85aab48274

@geometryolife 1361.6 STC https://stcscan.io/main/transactions/detail/0x09b3a3ff44923371d445dc996cf67e9edbbba43922477cfdbe23b805b5e061d7

**Pull request merged**
