### PR TITLE
member: zjhmale

### PR DESCRIPTION
**Pull request by zjhmale**

### CODE REVIEW

**Comment by yubing744** [comment]
@zjhmale Can you help to optimize [starcoin-ide](https://github.com/starcoinorg/starcoin-ide) together?

**Comment by yubing744** [comment]
@zjhmale Are you still going?

**Comment by yubing744** [comment]
@zjhmale I read your PRs, but none of them have been merged. You need to merge 3 PRs to graduate.

**Comment by zjhmale** [comment]
sure, kinda busy these days, will continue on the PRs shortly!

**Comment by zjhmale** [comment]
> @zjhmale Can you help to optimize [starcoin-ide](https://github.com/starcoinorg/starcoin-ide) together?
> 
> I am working on this: [starcoinorg/starcoin-ide#11](https://github.com/starcoinorg/starcoin-ide/issues/11) [move-language/move#218](https://github.com/move-language/move/pull/218)

sure, will keep an eye on this, great work!

**Pull request closed without merging**
